### ISSUE TITLE
Sr Admins is in the admins section twice. 

### ISSUE THREAD

**Issue by MelonicOverlord** [PedestriaMC-Network/PedestriapediaOfficial#13]

**Comment by Lukas-Batema** [comment]
Dear @MelonicOverlord, 
Thank you for your bug report! Could you next time have a more concise title, for example, “Duplicate Files,” and put the names and paths of those files in the description,p? Thanks!

Best Wishes,
Lukas Batema

**Comment by Lukas-Batema** [comment]
> Dear @MelonicOverlord,
> Thank you for your bug report! Could you next time have a more concise title, for example, “Duplicate Files,” and put the names and paths of those files in the description? Thanks!
> 
> Best Wishes,
> Lukas Batema

I do not see the issue here, there is a base html file named that, and then a folder, with the sr. Admin inside it. Could you put the path links for the two (or more) duplicate files? Is it inside of a certain file, like in the nav bar? If so, link that file singularly and say that in the comments below! Thanks!

Best Wishes,
Lukas Batema

**Comment by MelonicOverlord** [comment]
Have no idea where the file issues are, I went to where I thought they would be but there are no duplicates. 

![image](https://user-images.githubusercontent.com/73000042/104953791-fe4c3e80-59be-11eb-8a80-5b3e30133983.png)

**Comment by Lukas-Batema** [comment]
Dear @MelonicOverlord,
May I close this issue then?

Best Wishes,
Lukas Batema

**Comment by Lukas-Batema** [comment]
Closed issue cause no response
